Add Lab_4
sergey-berezin/441_nazarov pull request #4
Opened 2022-12-08 01:05 UTC by Nazacod

Добавлена лабораторная №4

2022-12-09 07:29 UTC, sergey-berezin requested changes

2022-12-09 07:29 UTC, sergey-berezin commented on Lab_4/Server/Controllers/WeatherForecastController.cs
> +// using Microsoft.AspNetCore.Mvc;
Надо удалить этот файл - его содержимое всё равно закомментировано.

2022-12-09 07:29 UTC, sergey-berezin commented on Lab_4/Server/Database/Interface.cs
> +    public class InMemoryDb : IImagesDb
Название класса вводит в заблуждение. Почему `InMemoryDb`, если данные хранятся в базе данных на диске?

2022-12-09 07:29 UTC, sergey-berezin commented on Lab_4/Client/Client/MainWindow.xaml.cs
> +                var response = await HttpClientJsonExtensions.PostAsJsonAsync(httpClient, "", img);
В задании требуется обрабатывать ошибки обращения к серверу, связанные с сетевыми проблемам, путём повторного обращения.

2022-12-09 07:29 UTC, sergey-berezin commented on Lab_4/Client/Client/MainWindow.xaml.cs
> +            catch
`catch` для всех исключений без обработки - очень плохая идея. Какое исключение здесь планируется "заглушить"?

2022-12-09 07:29 UTC, sergey-berezin commented on Lab_4/Client/Client/MainWindow.xaml.cs
> +                var response = await httpClient.GetAsync($"{url}/images");
В задании требуется обрабатывать ошибки обращения к серверу, связанные с сетевыми проблемам, путём повторного обращения.

2022-12-09 07:29 UTC, sergey-berezin commented on Lab_4/Client/Client/MainWindow.xaml.cs
> +                        var response_inner = await httpClient.GetAsync($"{url}/images/{val}");
В задании требуется обрабатывать ошибки обращения к серверу, связанные с сетевыми проблемам, путём повторного обращения.

2022-12-09 07:29 UTC, sergey-berezin commented on Lab_4/Client/Client/MainWindow.xaml.cs
> +            var response = await httpClient.DeleteAsync($"{url}/images");
В задании требуется обрабатывать ошибки обращения к серверу, связанные с сетевыми проблемам, путём повторного обращения.

2022-12-16 22:13 UTC, Nazacod commented
Добавил 5ую лабораторную

2022-12-19 08:28 UTC, sergey-berezin requested changes

2022-12-19 08:28 UTC, sergey-berezin commented on Lab_4/Client/Client/MainWindow.xaml.cs
> +                        MessageBox.Show("Not Hello!");
Какое действие вы ожидаете от политики повтора после выдачи этого сообщения?

2022-12-19 08:28 UTC, sergey-berezin commented on Lab_5/frontend/main.js
> +(function init () {
С какой целью сделан такой способ вызова кода инициализации?

2022-12-19 09:53 UTC, merged